### ISSUE TITLE
Maximum update depth exceeded.

### ISSUE THREAD

**Issue by meowtec** [react-component/tabs#147]
In the demo below, `ScrollableTabBarNode` will repeatedly call `componentDidUpdate` and `setState`.

```js

export default class App extends PureComponent {
  render() {
    return (
      <Tabs style={{ width: 450 }}>
        <Tabs.TabPane tab="四个汉字" key="1" />
        <Tabs.TabPane tab="汉字" key="2" />
        <Tabs.TabPane tab="四个汉字" key="3" />
        <Tabs.TabPane tab="四个汉字" key="4" />
      </Tabs>
    )
  }
}
``` 

```css

.ant-tabs .ant-tabs-bar .ant-tabs-nav-container-scrolling .ant-tabs-nav-scroll .ant-tabs-nav-animated {
  padding: 0 8px;
}

.ant-tabs .ant-tabs-bar .ant-tabs-nav-scroll .ant-tabs-nav {
  padding: 0 16px;
}
```
