### ISSUE TITLE
The animated tabpanes won't work out of the box

### ISSUE THREAD

**Issue by martin-braun** [react-component/tabs#351]
Hi,

I had to add this CSS to make it work: 

```css
.rc-tabs-content {
  display: flex;
  width: 100%;
}

.rc-tabs-content-animated {
  -webkit-transition: margin 0.3s;
  -moz-transition: margin 0.3s;
  -ms-transition: margin 0.3s;
  -o-transition: margin 0.3s;
  transition: margin 0.3s;
}

.rc-tabs-tabpane {
  width: 100%;
  flex: none;
}
```

I think it would be a good idea to add those style properties to the components by default. Also the whole tab bar is fully not styled at all. I understand why this is the case, but it would be great to package a stylesheet that has any beautiful predefined style that can be copied and modified for those who only need little changes.
